version: '2'

services:
  kuzzle:
    image: kuzzleio/kuzzle
    cap_add:
      - SYS_PTRACE
    depends_on:
      - redis
      - elasticsearch
    environment:
      - kuzzle_services__db__client__host=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - NODE_ENV=production
    volumes:
      - "./protocol-mqtt:/var/app/protocols/enabled/protocol-mqtt"
      - "./conf/.kuzzlerc:/etc/.kuzzlerc"
    ports:
      - "9000:1883"
    labels:
      consul.service: kuzzle
      consul.tags: kuzzle-kibana

  redis:
    image: redis:3.2
    labels:
      consul.skip: "true"

  elasticsearch:
    image: kuzzleio/elasticsearch:5.4.1
    environment:
      - cluster.name=kibana-elastic
      # disable xpack
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    labels:
      consul.skip: "true"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.1
    environment:
      - SERVER_HOST=0.0.0.0
    volumes:
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"
    labels:
      consul.service: web
      consul.tags: kibana-kuzzle
      consul.port: '5601'
